apiVersion: v1
kind: Pod
metadata:
  name: my-pod
  namespace: default
  labels:
    app: my-app
    env: dev
spec:
  containers:
    - name: my-container
      image: sonambewafaa/hellotondu:latest
      ports:
        - containerPort: 80