apiVersion: v1
kind: Service
metadata:
  name: my-service
  namespace: default
  labels:
    app: my-app
    env: dev
spec:
  ports:
    - port: 80
      targetPort: 8080
  selector:
    app: my-app
    