name: aks-deploy
on:
  push:
    branches:
    - master
    - release/

permissions:
  id-token: write
  contents: read
jobs: 
  firstjob:
    name: myfirstjob
    runs-on: ubuntu-latest
    environment:
      name: production_environment
    steps: 
    -  name: Azure Login
       uses: Azure/login@v2.3.0
       with:
         client-id: ${{ secrets.AZURE_CLIENT_ID }}
         tenant-id: ${{ secrets.AZURE_TENANT_ID }}
         subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
   
      
   
    
  
