name: aks-deploy
on:
  push:
    branches:
    - master
    - release/

jobs: 
  firstjob:
    name: myfirstjob
    runs-on: ubuntu-latest
    environment:
      name: production_environment
    steps: 
    -  name: Azure Login
       uses: Azure/login@v2.3.0
   
      
   
    
  
