name: aks-deploy
on:
  push:
    branches:
    - master
    - release/

permissions:
  id-token: write
  contents: read
jobs: 
  firstjob:
    name: myfirstjob
    runs-on: ubuntu-latest
    # environment:
    #   name: production_environment

    steps: 
    -  name: Azure Login
       uses: Azure/login@v2.3.0
       with:
         client-id: ${{ secrets.AZURE_CLIENT_ID }}
         tenant-id: ${{ secrets.AZURE_TENANT_ID }}
         subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

         
    -  name: Checkout
       uses: actions/checkout@v5.0.0

       
    -  name: Setup Terraform
       uses: hashicorp/setup-terraform@v3
       with:
         terraform_version: 1.7.5
    
    -  name: TerraformInit
       id: init
       run: terraform init -input=false  
       working-directory: aks
   
    -  name: TerraformPlan
       id: plan
       run: terraform plan -input=false
       working-directory: aks
       
  second-job:
    runs-on: ubuntu-latest
    name: apply
    needs: firstjob

    steps:
    -  name: Checkout
       uses: actions/checkout@v5.0.0
       
    -  name: terraformInit
       id: init
       run: terraform init -input=false
       working-directory: aks
       
    -  name: terraformApply
       id: apply
       run: terraform apply --auto-approve
       working-directory: aks
       
      
  
